#!/usr/bin/env bash
# Service control for an always-on neXal Mac, with tunnel state shown on startup.
#
#   bash scripts/mini-service.sh install     # write the LaunchAgent
#   bash scripts/mini-service.sh start       # start, then report the tunnel
#   bash scripts/mini-service.sh status      # agent, tunnel, GitHub runners
#   bash scripts/mini-service.sh stop | restart | logs | uninstall
#
# WHY THIS EXISTS RATHER THAN A BIGGER svc.sh. svc.sh belongs to the GitHub Actions
# runner: it is vendor code, regenerated by the runner package, and replaced on every
# runner upgrade. Editing it means the edits vanish at the least obvious moment. It
# also knows nothing about the connector or the tunnel. This is a separate script that
# reports on both and leaves svc.sh alone.
#
# WHERE TUNNEL STATE COMES FROM. Two independent sources, because they answer different
# questions and one of them works while the agent is stopped:
#
#   nexal tunnel-check    validates config, permissions, pinned version and re-hashes
#                         the binary. Answers "is this correctly set up".
#   tunnel-evidence.json  written beside config.json by `nexal run` on every observation
#                         (cmd/nexal/main.go). Answers "what is happening right now".
#
# Neither can report Verified or Attestation as true. Nothing in the codebase sets them
# true -- see internal/tunnel and its verificationGap. That is a deliberate floor, not a
# missing feature, and this script reports it rather than papering over it.
set -euo pipefail

LABEL="systems.nexal.connector"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
SUPPORT="$HOME/Library/Application Support/Nexal"
CONFIG="$SUPPORT/config.json"
EVIDENCE="$SUPPORT/tunnel-evidence.json"
LOG_DIR="$HOME/Library/Logs/Nexal"
# The DMG does NOT install anything into /usr/local/bin: package-app.sh places the CLI
# inside the bundle at Contents/Helpers/nexal. Defaulting to /usr/local/bin/nexal was
# simply wrong, so the real locations are searched in order -- an explicit NEXAL
# override, then $PATH, then the installed app, then a local build.
find_nexal() {
  if [ -n "${NEXAL:-}" ]; then printf '%s' "$NEXAL"; return; fi
  local c
  c="$(command -v nexal 2>/dev/null || true)"
  if [ -n "$c" ]; then printf '%s' "$c"; return; fi
  for c in \
    "/Applications/Nexal Connector.app/Contents/Helpers/nexal" \
    "$HOME/Applications/Nexal Connector.app/Contents/Helpers/nexal" \
    "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." 2>/dev/null && pwd)/build/Nexal Connector.app/Contents/Helpers/nexal" \
    "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." 2>/dev/null && pwd)/connector/nexal" \
    /usr/local/bin/nexal /opt/homebrew/bin/nexal; do
    [ -x "$c" ] && { printf '%s' "$c"; return; }
  done
  printf '%s' "nexal"
}
NEXAL="$(find_nexal)"

b()  { printf '\033[1m%s\033[0m\n' "$1"; }
ok() { printf '  \033[32m*\033[0m %s\n' "$1"; }
no() { printf '  \033[31mx\033[0m %s\n' "$1"; }
hm() { printf '  \033[33m!\033[0m %s\n' "$1"; }
plain() { printf '    %s\n' "$1"; }

have_python() { command -v python3 >/dev/null 2>&1; }

# Read one top-level string/bool/number from a flat JSON object. python3 when present;
# sed otherwise, so a clean macOS with no developer tools still gets a status output.
jget() {
  local file="$1" key="$2"
  [ -f "$file" ] || return 1
  if have_python; then
    python3 - "$file" "$key" <<'PY' 2>/dev/null || return 1
import json,sys
try:
    with open(sys.argv[1]) as f: d=json.load(f)
except Exception: sys.exit(1)
v=d.get(sys.argv[2])
if v is None: sys.exit(1)
print(str(v).lower() if isinstance(v,bool) else v)
PY
  else
    sed -n "s/.*\"$key\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$file" | head -1 | grep . || return 1
  fi
}

# Same, for one level of nesting. config.json holds the hostname at tunnel.hostname,
# not at the root: the python reader correctly returned nothing for a top-level lookup
# while the sed fallback matched it anyway, so the two readers disagreed and the
# hostname silently vanished on any Mac with python3 installed.
jget2() {
  local file="$1" outer="$2" key="$3"
  [ -f "$file" ] || return 1
  if have_python; then
    python3 - "$file" "$outer" "$key" <<'NESTED'
import json,sys
try:
    with open(sys.argv[1]) as f: d=json.load(f)
except Exception: sys.exit(1)
o=d.get(sys.argv[2])
if not isinstance(o,dict): sys.exit(1)
v=o.get(sys.argv[3])
if v is None: sys.exit(1)
print(str(v).lower() if isinstance(v,bool) else v)
NESTED
  else
    # Without python there is no cheap way to scope the match to the object, and a
    # root-level match would be wrong rather than merely imprecise. Report absence.
    return 1
  fi
}

require_config() {
  if [ ! -f "$CONFIG" ]; then
    no "No config at $CONFIG"
    plain "Run 'nexal init' first."
    exit 1
  fi
  # Load() reads through ReadPrivate, which refuses anything with group or other
  # permission bits. Catching it here explains it; the agent would just fail to start.
  local perm
  perm="$(stat -f '%Lp' "$CONFIG" 2>/dev/null || stat -c '%a' "$CONFIG" 2>/dev/null || echo '?')"
  if [ "$perm" != "600" ]; then
    hm "config.json is mode $perm; the connector requires 0600"
    plain "chmod 600 \"$CONFIG\""
  fi
}

tunnel_section() {
  b "TUNNEL"
  local host
  host="$(jget2 "$CONFIG" tunnel hostname 2>/dev/null || true)"
  if ! grep -q '"tunnel"' "$CONFIG" 2>/dev/null; then
    hm "No tunnel block in config.json -- this host has no incoming tunnel"
    plain "Add one with scripts/setup-cloudflared-origin.sh, then re-run install."
    return 0
  fi

  # Configuration and pin integrity. This re-hashes the binary, so it is the check
  # that catches a cloudflared replaced or upgraded underneath the pin.
  local check rc=0
  check="$("$NEXAL" tunnel-check 2>&1)" || rc=$?
  if [ $rc -ne 0 ]; then
    no "tunnel-check failed"
    printf '%s\n' "$check" | sed 's/^/    /'
  else
    local ver arch
    ver="$(printf '%s' "$check" | tr -d ' ' | sed -n 's/.*"version":"\([^"]*\)".*/\1/p')"
    arch="$(printf '%s' "$check" | tr -d ' ' | sed -n 's/.*"architecture":"\([^"]*\)".*/\1/p')"
    ok "pinned cloudflared ${ver:-?} ${arch:-?} -- digest, permissions and version verified"
  fi
  [ -n "$host" ] && plain "hostname $host"

  # Live observation, written by the supervising agent.
  if [ ! -f "$EVIDENCE" ]; then
    hm "No live evidence yet at tunnel-evidence.json"
    plain "It appears once 'nexal run' observes the tunnel. If the agent is running"
    plain "and this stays absent, cloudflared is not producing diagnostics."
    return 0
  fi

  local connected quarantined proto group last
  connected="$(jget "$EVIDENCE" connected || echo false)"
  quarantined="$(jget "$EVIDENCE" quarantined || echo false)"
  proto="$(jget "$EVIDENCE" observedProtocol || echo '')"
  group="$(jget "$EVIDENCE" observedKeyAgreement || echo '')"
  last="$(jget "$EVIDENCE" lastObservation || echo '')"

  local age=""
  if [ -n "$last" ] && have_python; then
    age="$(python3 - "$last" <<'PY' 2>/dev/null || true
import sys,datetime
try:
    t=datetime.datetime.fromisoformat(sys.argv[1].replace("Z","+00:00"))
    s=int((datetime.datetime.now(datetime.timezone.utc)-t).total_seconds())
    print(f"{s}s ago" if s<90 else (f"{s//60}m ago" if s<5400 else f"{s//3600}h ago"))
except Exception: pass
PY
)"
  fi

  if [ "$quarantined" = "true" ]; then
    # Quarantine is not cosmetic: the report callback in cmd/nexal/main.go calls
    # a.Cancel() on it, so the agent stops taking work.
    no "QUARANTINED -- the agent cancels work in this state"
    plain "Something in cloudflared's diagnostics was unsafe or ambiguous:"
    plain "a non-QUIC protocol, an http2 fallback, post-quantum disabled, an"
    plain "unrecognised key-agreement group, or malformed output."
    plain "Quarantine is sticky; restart the agent after fixing the cause."
  elif [ "$connected" = "true" ]; then
    ok "connected over ${proto:-?}${group:+, $group}${age:+ ($age)}"
    if [ -z "$group" ]; then
      hm "no key-agreement group observed yet -- QUIC alone is not proof of PQ"
    fi
  else
    hm "configured but not currently connected${age:+ (last observation $age)}"
  fi
  plain "verified=no attestation=no -- never true by design; local diagnostics are"
  plain "not remote attestation, so production dispatch stays gated."
}

agent_section() {
  b "CONNECTOR AGENT"
  if launchctl list 2>/dev/null | grep -q "$LABEL"; then
    local pid
    pid="$(launchctl list 2>/dev/null | awk -v l="$LABEL" '$3==l {print $1}')"
    if [ -n "$pid" ] && [ "$pid" != "-" ]; then ok "launchd: running (pid $pid)"; else hm "launchd: loaded but not running"; fi
  else
    no "launchd: not loaded -- run '$0 install' then '$0 start'"
  fi
  local listen; listen="$(jget "$CONFIG" listen 2>/dev/null || true)"
  if [ -n "$listen" ]; then
    if curl -fsS --max-time 3 "http://$listen/status" >/dev/null 2>&1; then
      ok "local API: $listen responding"
    else
      hm "local API: $listen not responding"
    fi
  fi
  local name paused; name="$(jget "$CONFIG" name 2>/dev/null || echo '?')"; paused="$(jget "$CONFIG" paused 2>/dev/null || echo '?')"
  plain "host \"$name\"  paused=$paused"
  [ "$paused" = "true" ] && plain "paused=true means this host contributes nothing until you resume it."
  return 0
}

runners_section() {
  b "GITHUB RUNNERS"
  command -v gh >/dev/null 2>&1 || { plain "gh not installed; skipping"; return 0; }
  local any=0
  for repo in nexal-ios nexal-platform nexal-connector; do
    local out
    out="$(gh api "repos/keithknott26/$repo/actions/runners" -q '[.runners[]|"\(.name) [\(.status)\(if .busy then ", busy" else ", idle" end)]"]|join(", ")' 2>/dev/null || echo "")"
    if [ -n "$out" ] && [ "$out" != "null" ]; then ok "$repo: $out"; any=1; else hm "$repo: no runner registered"; fi
  done
  [ $any -eq 1 ] || plain "Register one: REPO=keithknott26/<repo> bash setup-self-hosted-runner.sh"
  # A sleeping Mac does not fail a job, it queues it -- silently, for up to 24h.
  plain "A runner that is offline queues jobs rather than failing them."
}

cmd_install() {
  require_config
  if [ ! -x "$NEXAL" ]; then
    no "Cannot find the nexal CLI"
    plain "Looked for: nexal on PATH, then inside \"Nexal Connector.app/Contents/Helpers\""
    plain "(the DMG installs it there, NOT in /usr/local/bin), then a local build."
    plain ""
    plain "Point at it explicitly:"
    plain "  NEXAL=\"/Applications/Nexal Connector.app/Contents/Helpers/nexal\" $0 install"
    plain ""
    plain "Or build one from this checkout:"
    plain "  (cd connector && go build -o ./nexal ./cmd/nexal)"
    exit 1
  fi
  ok "Using $NEXAL"
  mkdir -p "$(dirname "$PLIST")" "$LOG_DIR"
  # KeepAlive restarts the agent if it exits. Deliberately NOT RunAtLoad-only: this is
  # a server. Quarantine cancels work inside the agent rather than exiting, so a restart
  # loop is not how that state is handled.
  cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$NEXAL</string>
    <string>run</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ProcessType</key><string>Background</string>
  <key>StandardOutPath</key><string>$LOG_DIR/connector.log</string>
  <key>StandardErrorPath</key><string>$LOG_DIR/connector.err.log</string>
</dict>
</plist>
PLIST_EOF
  ok "Wrote $PLIST"
  plain "Logs: $LOG_DIR/connector.log"
}

cmd_start() {
  require_config
  [ -f "$PLIST" ] || { no "Not installed. Run '$0 install' first."; exit 1; }
  # bootstrap is the modern verb; load is the deprecated one. Either can report
  # "Input/output error" purely because the job is ALREADY loaded, which is not a
  # failure -- so the outcome is confirmed below rather than inferred from exit status.
  launchctl bootstrap "gui/$(id -u)" "$PLIST" 2>/dev/null || launchctl load "$PLIST" 2>/dev/null || true
  launchctl kickstart "gui/$(id -u)/$LABEL" >/dev/null 2>&1 || true

  printf 'Starting %s' "$LABEL"
  local i
  for i in $(seq 1 15); do
    if launchctl list 2>/dev/null | grep -q "$LABEL"; then break; fi
    printf '.'; sleep 1
  done
  printf '\n\n'

  # The point of this script: wait for the tunnel to actually report, rather than
  # returning to a prompt that tells you nothing. Evidence is rewritten on every
  # observation, so a fresh mtime means the supervisor is alive.
  if grep -q '"tunnel"' "$CONFIG" 2>/dev/null; then
    printf 'Waiting for the tunnel to report'
    for i in $(seq 1 20); do
      if [ -f "$EVIDENCE" ] && [ "$(find "$EVIDENCE" -mtime -1m 2>/dev/null | wc -l)" -gt 0 ]; then break; fi
      printf '.'; sleep 1
    done
    printf '\n\n'
  fi
  cmd_status
}

cmd_stop() {
  launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || launchctl unload "$PLIST" 2>/dev/null || true
  ok "Stopped $LABEL"
}

cmd_restart() { cmd_stop; sleep 1; cmd_start; }

cmd_logs() {
  [ -f "$LOG_DIR/connector.log" ] || { no "No log yet at $LOG_DIR/connector.log"; exit 1; }
  tail -n "${2:-50}" -f "$LOG_DIR/connector.log"
}

cmd_uninstall() {
  cmd_stop
  rm -f "$PLIST"
  ok "Removed $PLIST"
  plain "config.json, the token file and cloudflared are left in place."
}

cmd_status() {
  require_config
  printf '\n'
  b "neXal service status -- $(date '+%Y-%m-%d %H:%M %Z')"
  printf '\n'
  agent_section; printf '\n'
  tunnel_section; printf '\n'
  runners_section; printf '\n'
}

case "${1:-status}" in
  install)   cmd_install ;;
  start)     cmd_start ;;
  stop)      cmd_stop ;;
  restart)   cmd_restart ;;
  status)    cmd_status ;;
  logs)      cmd_logs "$@" ;;
  uninstall) cmd_uninstall ;;
  *) echo "usage: $0 {install|start|stop|restart|status|logs|uninstall}"; exit 2 ;;
esac
